# Generated by Django 3.2.4 on 2021-06-11 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_productimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimages',
            name='more_images_url',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
