# Generated by Django 3.2.4 on 2021-06-11 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20210611_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='more_images',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='more_images_url',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
